import type { LucideIcon } from 'lucide-react';
import {
  Layers,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Search,
  User,
  ShoppingCart,
  MessagesSquare,
  MessageCircle,
  Crown,
  ArrowRight,
  Send,
  Globe,
  Package,
  Repeat,
  ShieldCheck,
  Truck,
  CalendarClock,
  Play,
  Pause,
  PiggyBank,
  Stethoscope,
  Gift,
  CreditCard,
  BadgeCheck,
  CircleCheck,
  Heart,
  Star,
  Plus,
  Minus,
  Check,
  PackageSearch,
  CalendarDays,
  Settings2,
  Settings,
  BadgePercent,
  Bell,
  Sparkles,
  Sparkle,
  Brush,
  ScanFace,
  HeartPulse,
  Moon,
  Award,
  FlaskConical,
  House,
  RefreshCw,
  Gem,
  BookOpen,
  Clock,
  LayoutDashboard,
  Target,
  MapPin,
  ZoomIn,
  TrendingUp,
  FolderTree,
  PackageOpen,
} from 'lucide-react';

/**
 * Name → Lucide icon map — the React equivalent of the Chewy kit's `VCIcon`
 * wrapper, so ported markup can keep using `<Icon name="…">`. Lucide is the
 * design-system's stated icon substitute for the (future) custom leaf-pill set.
 */
const MAP: Record<string, LucideIcon> = {
  layers: Layers,
  menu: Menu,
  x: X,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  search: Search,
  user: User,
  'shopping-cart': ShoppingCart,
  'messages-square': MessagesSquare,
  'message-circle': MessageCircle,
  crown: Crown,
  'arrow-right': ArrowRight,
  send: Send,
  globe: Globe,
  package: Package,
  repeat: Repeat,
  'shield-check': ShieldCheck,
  truck: Truck,
  'calendar-clock': CalendarClock,
  play: Play,
  pause: Pause,
  'piggy-bank': PiggyBank,
  stethoscope: Stethoscope,
  gift: Gift,
  'credit-card': CreditCard,
  'badge-check': BadgeCheck,
  'check-circle': CircleCheck,
  heart: Heart,
  star: Star,
  plus: Plus,
  minus: Minus,
  check: Check,
  'package-search': PackageSearch,
  'calendar-days': CalendarDays,
  'settings-2': Settings2,
  settings: Settings,
  'badge-percent': BadgePercent,
  bell: Bell,
  sparkles: Sparkles,
  sparkle: Sparkle,
  brush: Brush,
  'scan-face': ScanFace,
  'heart-pulse': HeartPulse,
  moon: Moon,
  award: Award,
  'flask-conical': FlaskConical,
  house: House,
  'refresh-cw': RefreshCw,
  gem: Gem,
  'book-open': BookOpen,
  clock: Clock,
  'layout-dashboard': LayoutDashboard,
  target: Target,
  'map-pin': MapPin,
  'zoom-in': ZoomIn,
  'trending-up': TrendingUp,
  'folder-tree': FolderTree,
  'package-open': PackageOpen,
};

/** Valid icon names (for admin pickers). */
export const ICON_NAMES = Object.keys(MAP);

export function Icon({
  name,
  size = 20,
  className = '',
  strokeWidth = 2,
  color,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
  color?: string;
}) {
  const C = MAP[name] ?? Package;
  return <C size={size} strokeWidth={strokeWidth} className={className} color={color} aria-hidden="true" />;
}
